server.port=${PORT}

spring.data.mongodb.uri=${MONGODB_URI}

spring.session.store-type=redis
spring.session.timeout=30m
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${REDIS_SSL}

epayco.customer-id=${EPAYCO_CUSTOMER_ID}
epayco.private-key=${EPAYCO_PRIVATE_KEY}
epayco.public-key=${EPAYCO_PUBLIC_KEY}
epayco.test-mode=${EPAYCO_TEST_MODE}
epayco.confirmation-url=${APP_URL}/payment/confirmation
epayco.response-url=${APP_URL}/payment/response

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000