name: CI Pipeline Spring Boot
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        java: [ '21', '24' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Build, test y verificar cobertura
        run: mvn -B clean verify

      - name: Publicar reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: reporte-jacoco-java${{ matrix.java }}
          path: target/site/jacoco

      - name: Verificar variable de entorno
        env:
          APP_ENV: ${{ secrets.APP_ENV_DEMO }}
        run: echo "Ejecutando en el ambiente configurado"